name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
          source-url: https://nuget.pkg.github.com/googolplex-s6/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore KwekkerCommon
      - name: Create the package
        run: dotnet pack --configuration Release KwekkerCommon
      - name: Publish the package to GPR
        run: dotnet nuget push KwekkerCommon/bin/Release/*.nupkg